wait(20)
loadstring(game:HttpGet("https://raw.githubusercontent.com/createdreallol/yessuh/refs/heads/main/gui.lua"))()
wait(1)
loadstring(game:HttpGet("https://raw.smokingscripts.org/vertex.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/createdreallol/yessuh/refs/heads/main/mm2.lua"))()
